id: IA91FBCA6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T15:35:17+00:00'
last_modified: '2022-06-08T13:43:58.422376+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ16920
  title: མན་ངག་རྒྱུད་ཀྱི་དཀའ་འགྲེལ་ལེགས་བཤད་གསེར་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CABA:
      image_group_id: I1KG13571
      title: ''
      total_pages: 882
      order: 1
      base_file: CABA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
