id: P010455
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:45.937375
source_metadata:
  id: bdr:W4CZ16920
  title: མན་ངག་རྒྱུད་ཀྱི་དཀའ་འགྲེལ་ལེགས་བཤད་གསེར་རྒྱན།
  author: ''
  volumes:
    2708337a450d4d3fad179bb26238fd74:
      image_group_id: I1KG13571
      title: ''
      volume_number: 1
      total_pages: 882
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
