id: P010455
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ16920
  title: མན་ངག་རྒྱུད་ཀྱི་དཀའ་འགྲེལ་ལེགས་བཤད་གསེར་རྒྱན།
  author: ''
  volumes:
    2708337a450d4d3fad179bb26238fd74:
      image_group_id: I1KG13571
      title: ''
      volume_number: 1
      total_pages: 882
      base_file: v001.txt
